version: '3.8'

services:
  pokemon-db:
    image: mongo:6.0.6
    container_name: ${MONGO_INITDB_DATABASE}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo/db:/mongo/db
    ports:
      - ${MONGO_PORT}:27017
